### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by brian-kephart** [owen2345/camaleon_oauth#13]
I installed this gem and ran `rails db:migrate`, and I enabled the plugin in /admin/plugins. However, the /admin/register screen is the same as before (no oauth options). Additionally, the documentation link in /admin/plugins doesn't work. Are there additional steps to install?

Rails 5.1.4
Ruby 2.4.2
Camaleon git version

**Comment by owen2345** [comment]
This plugin was for camaleon v1 (out of date)
